export type PostingEvent =
  | "PAYROLL_ACCRUAL" | "PAYROLL_PAYMENT" | "EXPENSE_ACCRUAL"
  | "COST_ACCRUAL" | "COST_PAYMENT"
  | "SETTLEMENT_ACCRUAL" | "SETTLEMENT_PAYMENT"
  | "ASSET_ACQUISITION" | "ASSET_PAYMENT" | "ASSET_DEPRECIATION" | "ASSET_DISPOSAL"
export const POSTING_EVENTS: PostingEvent[] = [
  "PAYROLL_ACCRUAL", "PAYROLL_PAYMENT", "EXPENSE_ACCRUAL",
  "COST_ACCRUAL", "COST_PAYMENT",
  "SETTLEMENT_ACCRUAL", "SETTLEMENT_PAYMENT",
  "ASSET_ACQUISITION", "ASSET_PAYMENT", "ASSET_DEPRECIATION", "ASSET_DISPOSAL",
]
export interface ResolvedRules { event: PostingEvent; byKey: Map<string, string> }
